#!/bin/sh

if [ "`hostname`" = "arrogant-bastard" ]
    then SEARCHPLACES="`find /home/rtucker/dev/* -maxdepth 0 -type d | xargs`"
elif [ "`hostname`" = "framboise" ]
    then SEARCHPLACES="${SEARCHPLACES} /var/www"
elif [ "`hostname`" = "rocwiki" ]
    then SEARCHPLACES="${SEARCHPLACES} /home/rocwiki/sycamore_base"
fi

SEARCHPLACES="${SEARCHPLACES} /etc"

for i in ${SEARCHPLACES}
do
    TEMPFILE=`tempfile`
    cd $i
    git status > ${TEMPFILE} 2>&1
    if [ $? != 128 ] && [ "`tail -1 ${TEMPFILE}`" != "nothing to commit (working directory clean)" ]
    then
        mail -s "`hostname`:$i git status" root < ${TEMPFILE}
    fi
    rm ${TEMPFILE}
done
 
